/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author andre
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form view
     */
    private ImageIcon icon;
    BufferedImage bffImg = null;
    BufferedImage bffImgModificada = null;

    public Principal() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_img_original = new javax.swing.JLabel();
        pn_img_original = new javax.swing.JScrollPane();
        lb_original = new javax.swing.JLabel();
        txt_img_modificada = new javax.swing.JLabel();
        pn_img_modificada = new javax.swing.JScrollPane();
        lb_modificado = new javax.swing.JLabel();
        bt_abrir = new javax.swing.JButton();
        bt_exportar = new javax.swing.JButton();
        pn_filtros = new javax.swing.JPanel();
        bt_negativo = new javax.swing.JButton();
        bt_log = new javax.swing.JButton();
        bt_log_inv = new javax.swing.JButton();
        bt_potencia = new javax.swing.JButton();
        bt_raiz = new javax.swing.JButton();
        bt_troca = new javax.swing.JButton();
        txt_filtro = new javax.swing.JLabel();
        pn_info = new javax.swing.JPanel();
        txt_coodernadas = new javax.swing.JLabel();
        txt_nivel_cinza = new javax.swing.JLabel();
        cmp_coodernadas = new javax.swing.JTextField();
        cmp_nivel_cinza = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cmp_tipo = new javax.swing.JTextField();
        txt_info = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txt_img_original.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt_img_original.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_img_original.setText("IMAGEM ORIGINAL");
        txt_img_original.setToolTipText("");

        pn_img_original.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lb_original.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lb_originalMouseMoved(evt);
            }
        });
        lb_original.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_originalMouseEntered(evt);
            }
        });
        pn_img_original.setViewportView(lb_original);

        txt_img_modificada.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt_img_modificada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_img_modificada.setText("IMAGEM MODIFICADA");
        txt_img_modificada.setToolTipText("");

        pn_img_modificada.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lb_modificado.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lb_modificadoMouseMoved(evt);
            }
        });
        pn_img_modificada.setViewportView(lb_modificado);

        bt_abrir.setText("Abrir");
        bt_abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_abrirActionPerformed(evt);
            }
        });

        bt_exportar.setText("Exportar");

        pn_filtros.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        bt_negativo.setText("Negativo");
        bt_negativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_negativoActionPerformed(evt);
            }
        });

        bt_log.setText("Logaritmo");
        bt_log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_logActionPerformed(evt);
            }
        });

        bt_log_inv.setText("Logaritmo Inverso");
        bt_log_inv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_log_invActionPerformed(evt);
            }
        });

        bt_potencia.setText("Potência");
        bt_potencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_potenciaActionPerformed(evt);
            }
        });

        bt_raiz.setText("Raiz");

        bt_troca.setText("Troca");
        bt_troca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_trocaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_filtrosLayout = new javax.swing.GroupLayout(pn_filtros);
        pn_filtros.setLayout(pn_filtrosLayout);
        pn_filtrosLayout.setHorizontalGroup(
            pn_filtrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_filtrosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_filtrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_log, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_negativo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_log_inv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_potencia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_raiz, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_troca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pn_filtrosLayout.setVerticalGroup(
            pn_filtrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_filtrosLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(bt_negativo)
                .addGap(18, 18, 18)
                .addComponent(bt_log)
                .addGap(18, 18, 18)
                .addComponent(bt_log_inv)
                .addGap(18, 18, 18)
                .addComponent(bt_potencia)
                .addGap(18, 18, 18)
                .addComponent(bt_raiz)
                .addGap(18, 18, 18)
                .addComponent(bt_troca)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        txt_filtro.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt_filtro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_filtro.setText("FILTROS");
        txt_filtro.setToolTipText("");

        pn_info.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txt_coodernadas.setText("COORDENADAS(X,Y):");

        txt_nivel_cinza.setText("NIVEL DE CINZA(RGB):");

        cmp_coodernadas.setEditable(false);
        cmp_coodernadas.setBackground(new java.awt.Color(255, 255, 255));

        cmp_nivel_cinza.setEditable(false);
        cmp_nivel_cinza.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("TIPO DE IMAGEM");

        cmp_tipo.setEditable(false);
        cmp_tipo.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pn_infoLayout = new javax.swing.GroupLayout(pn_info);
        pn_info.setLayout(pn_infoLayout);
        pn_infoLayout.setHorizontalGroup(
            pn_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_infoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pn_infoLayout.createSequentialGroup()
                        .addGroup(pn_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txt_coodernadas, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pn_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmp_coodernadas)
                            .addComponent(cmp_tipo, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)))
                    .addGroup(pn_infoLayout.createSequentialGroup()
                        .addComponent(txt_nivel_cinza)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmp_nivel_cinza, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_infoLayout.setVerticalGroup(
            pn_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_infoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmp_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pn_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_coodernadas)
                    .addComponent(cmp_coodernadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pn_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nivel_cinza)
                    .addComponent(cmp_nivel_cinza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        txt_info.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txt_info.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_info.setText("INFORMAÇÕES");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pn_info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_img_original, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                            .addComponent(pn_img_original, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                            .addComponent(bt_abrir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 24, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txt_filtro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pn_filtros, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_img_modificada, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                            .addComponent(pn_img_modificada, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                            .addComponent(bt_exportar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(txt_info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_img_original)
                    .addComponent(txt_img_modificada)
                    .addComponent(txt_filtro))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pn_img_original, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                            .addComponent(pn_img_modificada, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt_exportar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bt_abrir, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3))))
                    .addComponent(pn_filtros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_info)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pn_info, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_abrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_abrirActionPerformed
        JFileChooser arquivo = new JFileChooser();
        arquivo.setFileSelectionMode(JFileChooser.FILES_ONLY);

        int opc = arquivo.showOpenDialog(this);
        if (opc == JFileChooser.APPROVE_OPTION) {
            File file = arquivo.getSelectedFile();
            file = arquivo.getSelectedFile();

            try {
                bffImg = ImageIO.read(file);
                ImageIcon img_icon = new ImageIcon(bffImg);
                img_icon.setImage(img_icon.getImage().getScaledInstance(lb_original.getWidth(), lb_original.getHeight(), 0));
                lb_original.setIcon(img_icon);

            } catch (IOException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_bt_abrirActionPerformed

    private void lb_originalMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_originalMouseMoved
        // TODO add your handling code here:
        try {
            int coo_x, coo_y;
            coo_x = evt.getX();
            coo_y = evt.getY();

            Color cor = new Color(bffImg.getRGB(coo_x, coo_y));

            cmp_tipo.setText("Imagem Original");
            cmp_coodernadas.setText("x: " + Integer.toString(coo_x) + " y: " + Integer.toString(coo_y));
            cmp_nivel_cinza.setText("R: " + Integer.toString(cor.getRed())
                    + " G: " + Integer.toString(cor.getGreen())
                    + " B: " + Integer.toString(cor.getBlue()));

        } catch (Exception e) {
            System.out.println("");
        }


    }//GEN-LAST:event_lb_originalMouseMoved

    private void lb_originalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_originalMouseEntered
    }//GEN-LAST:event_lb_originalMouseEntered

    private void bt_negativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_negativoActionPerformed
        // TODO add your handling code here:
        bffImgModificada = new BufferedImage(bffImg.getWidth(), bffImg.getHeight(), BufferedImage.TYPE_INT_RGB);

        int valorR, valorG, valorB;

        for (int i = 0; i < bffImg.getHeight() - 1; i++) {
            for (int j = 0; j < bffImg.getWidth() - 1; j++) {
                Color cor = new Color(bffImg.getRGB(i, j));

                valorR = 255 - cor.getRed();
                valorG = 255 - cor.getGreen();
                valorB = 255 - cor.getBlue();

                cor = new Color(valorR, valorG, valorB);
                bffImgModificada.setRGB(i, j, cor.getRGB());
            }
        }

        ImageIcon img_icon = new ImageIcon(bffImgModificada);
        img_icon.setImage(img_icon.getImage().getScaledInstance(lb_modificado.getWidth(), lb_modificado.getHeight(), 0));
        lb_modificado.setIcon(img_icon);
    }//GEN-LAST:event_bt_negativoActionPerformed

    private void bt_logActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_logActionPerformed
        bffImgModificada = new BufferedImage(bffImg.getWidth(), bffImg.getHeight(), BufferedImage.TYPE_INT_RGB);
        int valorR, valorG, valorB;

        for (int i = 0; i < bffImg.getHeight() - 1; i++) {
            for (int j = 0; j < bffImg.getWidth() - 1; j++) {
                Color cor = new Color(bffImg.getRGB(i, j));

                valorR = (int) (105.886 * Math.log10(1 + cor.getRed()));
                valorG = (int) (105.886 * Math.log10(1 + cor.getGreen()));
                valorB = (int) (105.886 * Math.log10(1 + cor.getBlue()));

                cor = new Color(valorR, valorG, valorB);
                bffImgModificada.setRGB(i, j, cor.getRGB());
            }
        }

        ImageIcon img_icon = new ImageIcon(bffImgModificada);
        img_icon.setImage(img_icon.getImage().getScaledInstance(lb_modificado.getWidth(), lb_modificado.getHeight(), 0));
        lb_modificado.setIcon(img_icon);
    }//GEN-LAST:event_bt_logActionPerformed

    private void bt_trocaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_trocaActionPerformed
        bffImg = bffImgModificada;
        ImageIcon img_icon = new ImageIcon(bffImg);
        img_icon.setImage(img_icon.getImage().getScaledInstance(lb_original.getWidth(), lb_original.getHeight(), 0));
        lb_original.setIcon(img_icon);
    }//GEN-LAST:event_bt_trocaActionPerformed

    private void bt_log_invActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_log_invActionPerformed
        bffImgModificada = new BufferedImage(bffImg.getWidth(), bffImg.getHeight(), BufferedImage.TYPE_INT_RGB);
        int valorR, valorG, valorB;

        for (int i = 0; i < bffImg.getHeight() - 1; i++) {
            for (int j = 0; j < bffImg.getWidth() - 1; j++) {
                Color cor = new Color(bffImg.getRGB(i, j));

                valorR = (int) Math.pow(10, (cor.getRed() / 105.886));
                valorG = (int) Math.pow(10, (cor.getRed() / 105.886));
                valorB = (int) Math.pow(10, (cor.getRed() / 105.886));

                cor = new Color(valorR, valorG, valorB);
                bffImgModificada.setRGB(i, j, cor.getRGB());
            }
        }

        ImageIcon img_icon = new ImageIcon(bffImgModificada);
        img_icon.setImage(img_icon.getImage().getScaledInstance(lb_modificado.getWidth(), lb_modificado.getHeight(), 0));
        lb_modificado.setIcon(img_icon);
    }//GEN-LAST:event_bt_log_invActionPerformed

    private void lb_modificadoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_modificadoMouseMoved
        try {
            int coo_x, coo_y;
            coo_x = evt.getX();
            coo_y = evt.getY();

            Color cor = new Color(bffImgModificada.getRGB(coo_x, coo_y));
            cmp_tipo.setText("Imagem Modificada");
            cmp_coodernadas.setText("x: " + Integer.toString(coo_x) + " y: " + Integer.toString(coo_y));
            cmp_nivel_cinza.setText("R: " + Integer.toString(cor.getRed())
                    + " G: " + Integer.toString(cor.getGreen())
                    + " B: " + Integer.toString(cor.getBlue()));

        } catch (Exception e) {
            System.out.println("");
        }
    }//GEN-LAST:event_lb_modificadoMouseMoved

    private void bt_potenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_potenciaActionPerformed
        float gama = Integer.parseInt(JOptionPane.showInputDialog("Informe o valor de gama:"));
        bffImgModificada = new BufferedImage(bffImg.getWidth(), bffImg.getHeight(), BufferedImage.TYPE_INT_RGB);
        int valorR, valorG, valorB;

        for (int i = 0; i < bffImg.getHeight() - 1; i++) {
            for (int j = 0; j < bffImg.getWidth() - 1; j++) {
                Color cor = new Color(bffImg.getRGB(i, j));

                valorR = (int) (Math.pow(cor.getRed() / 255, gama) * 256);
                valorG = (int) (Math.pow(cor.getGreen()/ 255, gama) * 256);
                valorB = (int) (Math.pow(cor.getBlue() / 255, gama) * 256);

                cor = new Color(valorR, valorG, valorB);
                bffImgModificada.setRGB(i, j, cor.getRGB());
            }
        }

        ImageIcon img_icon = new ImageIcon(bffImgModificada);
        img_icon.setImage(img_icon.getImage().getScaledInstance(lb_modificado.getWidth(), lb_modificado.getHeight(), 0));
        lb_modificado.setIcon(img_icon);
    }//GEN-LAST:event_bt_potenciaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_abrir;
    private javax.swing.JButton bt_exportar;
    private javax.swing.JButton bt_log;
    private javax.swing.JButton bt_log_inv;
    private javax.swing.JButton bt_negativo;
    private javax.swing.JButton bt_potencia;
    private javax.swing.JButton bt_raiz;
    private javax.swing.JButton bt_troca;
    private javax.swing.JTextField cmp_coodernadas;
    private javax.swing.JTextField cmp_nivel_cinza;
    private javax.swing.JTextField cmp_tipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lb_modificado;
    private javax.swing.JLabel lb_original;
    private javax.swing.JPanel pn_filtros;
    private javax.swing.JScrollPane pn_img_modificada;
    private javax.swing.JScrollPane pn_img_original;
    private javax.swing.JPanel pn_info;
    private javax.swing.JLabel txt_coodernadas;
    private javax.swing.JLabel txt_filtro;
    private javax.swing.JLabel txt_img_modificada;
    private javax.swing.JLabel txt_img_original;
    private javax.swing.JLabel txt_info;
    private javax.swing.JLabel txt_nivel_cinza;
    // End of variables declaration//GEN-END:variables
}
